version: '3.4'

services:

  couchbase:
    image: couchbase/server:enterprise-5.1.0
    ports:
      - "8091-8094:8091-8094"
      - "11210:11210"
    volumes: 
      - ./server/data:/opt/couchbase/var      
    container_name: couchbase  
      
  sync-gateway:
    image: couchbase/sync-gateway:2.0.0-devbuild-enterprise
    ports: 
      - "4984-4985:4984-4985"
    command: -adminInterface :4985 /etc/sync-gateway/sync-gateway.json
    volumes: 
      - ./sync-gateway/data:/opt/couchbase-sync-gateway/data
      - ./sync-gateway/logs:/var/log/sync_gateway
      - ./sync-gateway/enders-game-sync.json:/etc/sync-gateway/sync-gateway.json
    container_name: sync-gateway
    depends_on:
      - couchbase
      - setup-sync-gateway

  setup-sync-gateway:
    image: couchbase/sync-gateway:2.0.0-devbuild-enterprise
    command: '/bin/bash ./usr/local/bin/setup-sync-gateway.sh'
    volumes: 
      - './sync-gateway/setup-sync-gateway.sh:/usr/local/bin/setup-sync-gateway.sh'
    container_name: setup-sync-gateway
    depends_on:
      - couchbase

networks:
  default:
    external:
      name: enders-game-net  